apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ak-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      imagePullSecrets:
      - name: ecr-secret
    spec:
      containers:
      - name: web-app
        image: 225989348530.dkr.ecr.us-east-1.amazonaws.com/app/webappnew:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer-svc
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer